zuul:
  #默认Zuul认为请求头中 "Cookie", "Set-Cookie", "Authorization" 是敏感信息，它不会转发
   #请求，因为把它设置为空，就会转发了
  sensitive-headers: null
  add-host-header: true #正确的处理重定向操作
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  routes:
    api-hello-service:
      path: /hello-service/**
      serviceId: hello-service
    api-ribbon-consumer:
      path: /ribbon-consumer/**
      serviceId: ribbon-consumer
    api-feign-consumer:
      path: /feign-consumer/**
      serviceId: feign-consumer
    api-config-consumer:
      path: /config/**
      serviceId: config-server
    api-content-manage:
        path: /content-manage/**
        serviceId: content-manage
    api-sso-server:
      path: /sso-server
      serviceId: sso-server
ribbon:
  ConnectTimeout: 15000 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)
hystrix:
  command:
    default:
    execution:
    isolation:
    thread:
    timeoutInMilliseconds: 60000 # 设置hystrix的超时时间为6000ms
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
sso:
  client-id: sharecesuo
  client-secret: 123456
  access-token-uri: http://192.168.1.100:8000/oauth/token
  user-info-uri: http://192.168.1.100:8002/userInfo
logging:
  level:
    org.springframework.security: debug
