spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content-manage?user=root&amp;password=root&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true
    username: root
    password: root
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

web:
  upload-path: D:/

management:
  endpoints:
    web:
      exposure:
        include: 'refresh'
logging:
  level:
    org.springframework.security: debug

#security:
#    oauth2:
#        client:
#            client-id: sharecesuo
#            client-secret: 123456
#            user-authorization-uri: http://192.168.1.100:8000/oauth/authorize #授权码端点
#            registered-redirect-uri: http://192.168.1.100:10001/login
#            access-token-uri: http://192.168.1.100:8000/oauth/token #令牌断点
##            token-name: access_token
##            authentication-scheme: query
##            client-authentication-scheme: form
#        resource:
##            token-info-uri: http://192.168.1.100/oauth/check_token
#            jwt:
#                key-uri: http://192.168.1.100:8000/oauth/token_key
#server:
#    servlet:
#        session:
#            cookie:
#                name: OAUTH2SESSION
