spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security?user=root&amp;password=Wdx123123123.&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true
    username: root
    password: Wdx123123123.
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置，在DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    redis:
        database: 10
        host: localhost
        port: 6379
mybatis-plus:
    global-config:
        db-config:
            id-type: auto
            logic-delete-field: del
            logic-delete-value: 1
            logic-not-delete-value: 0
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.study.ssoserver.entity
#暴漏所有的端点
management:
    endpoints:
        web:
            exposure:
                include: "*"
logging:
  level:
    org.springframework.security.oauth2: debug